### ISSUE TITLE
Increment

### ISSUE THREAD

**Issue by logikv** [mvcbox/sql-query#2]
Здравствуйте. А как можно при update увелчить нынешнее значение ''+$var?

        $result = qb()->table('table')->where(array(
            'tr1' => $social,
            'tr2' => $group_name
        ))->update(array(
            'tr3' => 'tr3'+$var
        ));

**Comment by mvcbox** [comment]
Здравствуйте. Попробуйте так:

```php
$result = qb()->table('table')->where(array(
        'tr1' => $social,
        'tr2' => $group_name
    ))->update(array(
        'tr3' => qb()->expr('`tr3` + ' . $var)
    ));
```
